version: '3.6'
services: 
    postgres:
        image: postgres:13.3
        restart: always
        environment: 
            - DATABASE_HOST=127.0.0.1
            - POSTGRES_USER=Viking
            - POSTGRES_PASSWORD=Viking
            - POSTGRES_DB=Viking

        ports:
            - "5439:5432"
        volumes:
            - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql